// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResourceCenter.Data;

#nullable disable

namespace ResourceCenter.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240418160710_sqlite.local_migration_146")]
    partial class sqlitelocal_migration_146
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ResourceCenter.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Area")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Closed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Opened")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Number");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ResourceCenter.Models.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Number")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("FullName", "Number");

                    b.ToTable("Residents");
                });

            modelBuilder.Entity("ResourceCenter.Models.ResidentAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResidentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "ResidentId");

                    b.HasIndex("ResidentId");

                    b.ToTable("ResidentAccounts");
                });

            modelBuilder.Entity("ResourceCenter.Models.ResidentAccount", b =>
                {
                    b.HasOne("ResourceCenter.Models.Account", "Account")
                        .WithMany("ResidentAccounts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResourceCenter.Models.Resident", "Resident")
                        .WithMany("ResidentAccounts")
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Resident");
                });

            modelBuilder.Entity("ResourceCenter.Models.Account", b =>
                {
                    b.Navigation("ResidentAccounts");
                });

            modelBuilder.Entity("ResourceCenter.Models.Resident", b =>
                {
                    b.Navigation("ResidentAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
